### ISSUE TITLE
Eslint configuration

### ISSUE THREAD

**Issue by pwnreza** [mongkuen/gatsby-plugin-root-import#13]
Hi there,

I am a gatsby beginner and added the plugin with following settings to my gatsby-config.js in order to allow root imports:
```
{
    resolve: 'gatsby-plugin-root-import',
    options: {
        src: path.join(__dirname, 'src'),
        components: path.join(__dirname, 'src/components'),
        graphql: path.join(__dirname, 'src/graphql'),
        images: path.join(__dirname, 'src/images'),
        layouts: path.join(__dirname, 'src/layouts'),
        pages: path.join(__dirname, 'src/pages'),
        services: path.join(__dirname, 'src/services'),
        utils: path.join(__dirname, 'src/utils'),
    },
}
```

The root import itself is working but I have errors regarding eslint. I am using vscode btw.
I tried adding alias settings to my .eslintrc like described [here](https://stackoverflow.com/questions/61484861/how-to-use-absolute-imports-in-gatsby-with-eslint).
So I added the following settings to my .eslintrc
```
"settings": {
    "import/resolver": {
      "node": {
        "paths": ["src", "node_modules"]
      },
      "alias": {
        "map": [
          ["src", "./src"],
          ["components", "./src/components"],
          ["graphql", "./src/graphql"],
          ["images", "./src/images"],
          ["layouts", "./src/layouts"],
          ["pages", "./src/pages"],
          ["services", "./src/services"],
          ["utils", "./src/utils"]
       ]
      }
    }
  }
```

Also tried it without the "node" settings.
I am probably not the first trying to run gatsby root imports with eslint and vscode. Is it possible for someone who is running a similar setup to share his experience and/or settings?

Best regards

**Comment by pwnreza** [comment]
Bump. Does anyone habe a clue?

**Comment by mongkuen** [comment]
The answer [you linked](https://stackoverflow.com/a/61487498/2957639) was correct. Using `eslint-import-resolver-alias` with these settings should resolve the issue 

```
  "settings": {
    "import/resolver": {
      "alias": {
        "map": [
            ["src", "./src"],
            ["components", "./src/components"],
            // ... etc etc for each alias you have
         ],
         "extensions": [".js", ".jsx"]
      }
    },
  },
```
