### ISSUE TITLE
Resolve path to unit test

### ISSUE THREAD

**Issue by jephjohnson** [mongkuen/gatsby-plugin-root-import#9]
When running my app, everything is running fine as expected. However, if I run a test using jest, the test can't make the connection of the path in my gatsby config file. Below is a hiearchy of what I am running into.

gatsby-config:

```
...

{
      resolve: "gatsby-plugin-root-import",
      options: {
        reducers: path.join(__dirname, "src/reducers"),
        sagas: path.join(__dirname, "src/sagas"),
        web: path.join(__dirname, "src/web"),
        test: path.join(__dirname, "src/web"), <-------- test cases don't live on the root
      },
    },

....
```

<img width="151" alt="Screen Shot 2020-08-13 at 10 46 17 AM" src="https://user-images.githubusercontent.com/1817084/90157009-cdeadf00-dd52-11ea-99f9-0106c4ea6f63.png">

```
Test Error:

● Test suite failed to run

    Cannot find module 'web/components/graphs/line-graph' from 'src/web/components/card/index.js'

    Require stack:
      src/web/components/card/index.js
      src/web/components/card/test/index.test.js

      1 | import React from "react"
      2 | import { string, array } from "prop-types"
    > 3 | import LineGraph from "web/components/graphs/line-graph"
```

**Comment by jephjohnson** [comment]
Bump - Any workarounds on this?

**Comment by agwisniewska** [comment]
Yes, I've encountered the same problem.

**Comment by agwisniewska** [comment]
I've found a solution, in `jest.config.js` file inside `moduleNameMapper` I've added my aliases.

Please take a look. 

```moduleNameMapper: {
    "@commons/(.*)": "<rootDir>/src/components/commons/$1",
    "@components/(.*)": "<rootDir>/src/components/$1",
    ".+\\.(css|styl|less|sass|scss)$": `identity-obj-proxy`,
    ".+\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": `<rootDir>/__mocks__/file-mock.js`,
  },```

**Comment by filhodoto** [comment]
Hey @jephjohnson , I had the same problem and found my solution here #8 .
@mongkuen any reason why this hasn't been committed yet? As of today this was the solution to my problem with using gatsby-plugin-root-import with Jest

**Comment by mongkuen** [comment]
This plugin lets webpack correctly compile the aliases, but it doesn't mean that jest will know what those aliases mean when you run your tests

@filhodoto is right, you'll have to set up Jest properly, using [`moduleNameMapper`](https://jestjs.io/docs/en/configuration.html#modulenamemapper-objectstring-string--arraystring).

I've added a little section in the new README to clarify this for newcomers. Thanks for bringing it to my attention!
